brew install --cask nikitabobko/tap/aerospace
brew install bat
brew install btop
brew install coreutils
brew install eza
brew install gh
brew install gnu-sed
brew install gnu-sed 
brew install gnu-tar 
brew install goreleaser
brew install gpg
brew install grep 
brew install gzip
brew install hashicorp/tap/vault
brew install helm
brew install ipcalc
brew install iproute2mac
brew install jq 
brew install keychain
brew install kind
brew install neovim
brew install obs
brew install obsidian
brew install openssl
brew install opentofu
brew install orbstack
brew install s5cmd
brew install stow
brew install syncthing
brew install tmux
brew install uv
brew install watch
brew install yq
