#!/bin/bash

GREEN='\033[1;32m'
BLUE='\033[1;34m'
RED='\033[1;30m'
NC='\033[0m'

pushd $(dirname $(readlink -f $0))

echo -e "${BLUE}Stashing existing changes...${NC}\n"
stash_result=$(git stash push -m "sync-dotfiles: Before syncing dotfiles")
needs_pop=1
if [ "$stash_result" = "No local changes to save" ]; then
   needs_pop=0
fi

echo -e "${BLUE}Pulling updates from dotfiles repo...${NC}\n"
git pull origin master
echo

if [[ $needs_pop -eq 1 ]]; then
   echo -e "${BLUE}Popping stashed changes...${NC}\n"
   git stash pop
fi

unmerged_files=$(git diff --name-only --diff-filter=U)
if [[ ! -z $unmerged_files ]]; then
   echo -e "${RED}The following files have merge conflicts after popping the stash:${NC}\n"
   printf %"s\n" $unmerged_files # Ensure newlines are printed
else
   echo -e "${BLUE}Run stow to ensure all new dotfiles are linked.${NC}"
   # Run stow to ensure all new dotfiles are linked
   for package in */; do
      echo -e "${BLUE}Stow package: ${package}${NC}"
      stow -t ~ $package
   done
fi

popd
